### ISSUE TITLE
Feedback on page: PTW X RyuCon

### ISSUE THREAD

**Issue by iwulOG** [k3rni/teczki-polskiego-wrestlingu#11]
**Which page ?** `e/2023-07-16-ptw-x-ryucon.md`
**Your feedback:**
<Add location: Tauron Arena Kraków. This was PTW's Ryucon return, this time taking a main part of the arena (as opposed to previous year's smaller hall on the side). The show featured references to the manga convention, including custom, manga-inspired entrances.

Johnny Storm def. Axel Fox. 
*Storm came out to Mortal Kombat theme
Marco Hammers (w/Karyna) def Boro. 
*Olgierd interfered, allowing Marco to hit a low-blow on his opponent
**Boro came out to Initial D theme "Deja Vu"
Syriusz Dziedzic def. Marcelito
*After getting kidnapped and held captive by Sinister, returning Dziedzic appears as Sinister's ally, with a changed look, theme song and new, more aggressive moveset. In post-match interview (conducted by Tobiasz "Skyver" Korzybski), Sinister answers all the questions, does not allow Dziedzic to speak, announces baptism of Dziedzic for next Underground show
Diana Strong def. Vic Golden
*Golden came out alone, without Gabriel Queen in his corner.
Karol "Iskra" Górski comes out after the match, challenging Diana to the match for next Underground
Krampus (w/Sinister and Syriusz Dziedzic) def. Samson 
*Post-match attack on Samson by Sinister and his allies, Marcelito tries to make a save but gets beaten down as well. The light goes off and Nano Lopez makes a save with a steel chair
"Starboy" Nano Lopez def. Olgierd (w/Karyna)
Puncher cuts a promo, insulting manga culture and funs, burning manga books in a bucket full of gasoline. Member of the staff extinguishes the fire
Puncher def. Sam Rogers (aka Sam Della Valle)
Wiktor Longman makes an entrance to interrupt Pan Pawłowski. He confirms cutting ties with John "Bad Bones" Klinger and proclaims loyalty to Pawłowski
PTW Tag Team Championship match: Budapest Bastards v Paka (c) ends in no contest 
*Paka made an entrance to Attack on Titan theme "Shinzo wo Sasageyo!"
**due to both teams getting attacked by Legia Łysych (Olgierd and Hammers) and Vic Golden, the champions retain. Both teams chase off the heels, the show ends with the babyfaces standing tall.
Add references:
[Full event on Youtube](https://www.youtube.com/watch?v=jOr7PhKb7xY&t=6971s) (requires paid subscription)
[Full event on Fite/Triller](https://www.trillertv.com/watch/ptw-ryucon/2pddh/) (requires paid subscription)
Sinister sings Radiohead's "Creep" to captive Dziedzic: "https://www.youtube.com/watch?v=WU5OTqZDUtY&pp=ygUOc2luaXN0ZXIgY3JlZXA%3D">

**Comment by k3rni** [comment]
Added in e3701dd.
