### ISSUE TITLE
Feedback on page: PTW

### ISSUE THREAD

**Issue by iwulOG** [k3rni/teczki-polskiego-wrestlingu#12]
Add event description:
This was the 4th of PTW major events and the first one to air on paid Youtube. The event sparked controversy due lower starpower than previous three major events (a result of titular sponsor, Kinguin, pulling off) and transmission cutting off. The Final Cut, rid of quality issues has later been released (24 Aug 2023).
The event came from Czasoprzestrzeń in Wrocław, a venue associated with other promotion, Maniac Zone Wrestling.
Cryptic promos from Sinister aired all throughout the build-up to the show.

Add match card:
no#1 contender's for PTW Tag Team Championship Match:
Budapest Bastards def. Axel Fox & Johnny Storm - new #1 contenders
*after Justin Joy leaving, Axel Fox was left without a tag team partner. The match was announced as Axel Fox & mystery partner of his choosing v Budapest Bastards

Olgierd (w/Karyna) def. Boro 
*Marco Hammers interferes on Olgierd's behalf. They form a tag team and declare their wish to win PTW Tag Team Championship

Diana Strong def. Amale

Krampus (w/Sinister) def. Peter Tihanyi

Nano Lopez appears on the stage and challenges Krampus to a match.

After a break, Karol "Iskra" Górski enters the ring, carrying a petition for a match. The match is denied, Iskra watches the next match from ringside.

Samson def. Marcelito

Wiktor Longman def. Rafi Rarytas

Rafi Rarytas gets taken away on the stretcher, Longman cuts a promo discussing the result of his match. He calls out Syriusz Dziedzic to the ring and after a brief promo exchange lays him out with At Your Service. Dziedzic recovers and pushes away Pawłowski, takes a microphone and calls out to Sinister.

"I've got you babe" promo from Sinister plays, as he makes his entrance with Krampus, it is revealed that subject of the promo was Sinister's offer for Dziedzic to join him. Sinister picks up Dziedzic for a hug and Krampus hits his finisher on Dziedzic. They make their leave with Krampus carrying Dziedzic out.

DPW Championship Match: Robert Star (c) retains against Dawid "Puncher" Seńko
*after interference from Sędzia Rafał, countered by Malczyński brothers hitting him with superkicks.
**Paweł "Boryss" Borkowski was a special commentator

Finals of tournament for PTW Tag Team Championship, Tables match:
Paka (Disco Pablo and Taras) def. Pure Gold (Gabriel Queen and Vic Golden) to become inaugural PTW Tag Team Champions.
*Paka made a special entrance to Scooby Doo theme, driving a Mystery Machine
**Olgierd and Hammers make an interference after referee Seweryn gets laid out. Boro enters to chase Olgierd and Hammers off with a kendo stick

Pawłowski is in ring to close the show. Fired John "Bad Bones" Klinger appears on the big screen. He requests Pawłowski to reinstate him and give him a title match. After an initial rejection, he reveals a chair with tied up Marcin "Rzeźnik" Rzeźniczek (the other owner of PTW) behind him. Klinger beats up on Rzeźniczek and after threatening to cut off his fingers with pliers. This makes Pawłowski reinstate Klinger. "Bad Bones" lays out Rzeźniczek with a punch and carries him, stunned and tied up to the entrance stage. Pawłowski sends the security team, who chase Bones off. The show ends with Pawłowski checking on Rzeźniczek.

Add references:
[Full event on Youtube](https://www.youtube.com/watch?v=bjeXfDhVFJY&t=11451s) (requires paid subscription)
[Full event on Youtube - final cut](https://www.youtube.com/watch?v=q8k7UEDEXxI&t=3879s)
[Full event on Fite/Triller](https://www.trillertv.com/watch/ptw-4-the-mystery/2pd8e/) (requires paid subscription)

**Comment by k3rni** [comment]
Updated in 51ff3b4.
