### ISSUE TITLE
Feedback on page: PTW 

### ISSUE THREAD

**Issue by iwulOG** [k3rni/teczki-polskiego-wrestlingu#13]
Mutant was last seen in PTW on their very first event in 2021. Taxi Złotówa was officially suspended by Pawłowski. Arczi Czajka is another character seen only on the first show so far. - are we skipping Undergrounds? Czajka also appeared at first PTW Underground and PTW Underground 2

also, spelling:
Andrzej Supro**n** has no "ń" in his name.

**Comment by k3rni** [comment]
Updated in 3408aa6
