### ISSUE TITLE
Feedback on page: PpW Supershow

### ISSUE THREAD

**Issue by iwulOG** [k3rni/teczki-polskiego-wrestlingu#16]
**Which page ?** `e/2021-07-30-ppw-poznan-supershow.md`
**Your feedback:**
<error correction:
"PPW would return to that event two years later at [Piwo Przyjacielem Wrestlingu](https://teczki-polskiego-wrestlingu.pages.dev/e/2023-11-24-ppw-piwo-przyjacielem-wrestlingu/), and _they would hold another co-branded show later that same year_ ([Żadnych Granic](https://teczki-polskiego-wrestlingu.pages.dev/e/2023-09-23-ppw-mzw-zadnych-granic/))
to:
PPW would return to that event two years later at [Piwo Przyjacielem Wrestlingu](https://teczki-polskiego-wrestlingu.pages.dev/e/2023-11-24-ppw-piwo-przyjacielem-wrestlingu/), _following another co-branded show held in September the same year_ ([Żadnych Granic](https://teczki-polskiego-wrestlingu.pages.dev/e/2023-09-23-ppw-mzw-zadnych-granic/))..">

**Comment by iwulOG** [comment]
wrong timeline order:
Piwo przyjacielem wrestlingu: 2023-11-24 (and 25, two night event)
MZW+PpW Żadnych Granic: September 23, 2023

**Comment by k3rni** [comment]
Updated in 42b829b.
