### ISSUE TITLE
Feedback on page: Prime Time Wrestling

### ISSUE THREAD

**Issue by iwulOG** [k3rni/teczki-polskiego-wrestlingu#18]
**Which page ?** `o/ptw.md`
**Your feedback:**
<add to history:
On 28.06.2021, Arkadiusz Pan Pawłowski, an experienced, yet polarizing figure on the Polish scene, announced the launch of his own wrestling promotion, promising "a new quality of entertainment". He posted a trailer [https://www.facebook.com/watch/?v=343114510600555&ref=sharing] featuring himself and glimpses of various wrestlers.
Over the course of summer, training events have been held and social media promotion continued. Eventually, the first show was announced, named PTW: Revolucja. Gradually, the competitors have been revealed, featuring veterans of Polish scene, debuting Polish wrestlers and foreign guests.

2023 name change:
Also known as Kinguin Prime Time Wrestling. On 21st of September 2021, Kinguin was announced as one of the sponsors [https://www.facebook.com/PrimeTimeWrestlingPL/posts/pfbid02jM7go32wEREc9u2XofEbKhhHFhHohQ16Cb6dhCHXzQURZUZYGhzzeXCcDfu6x9k3l?__cft__[0]=AZW8RSEs3YI8N65sk1-qODaZtstz8q87cFz_JboMMhu0JvJhfYDq6AMZSnZYH1pCJAHw_2M1gqZf40JdApLpOdukt1nBntJkbfLGep7sGrIlBJI6CUlbQBjpzYro9ABmdjLDAXJW_WdOC9c1jNRts7_vICZvxUljJvZV6CO8Ym1587yJf-Ya-Qd4L5XkBo81IQ0&__tn__=%2CO%2CP-R] and later became a titular one, was added to the promotion's logo. Kinguin mascot became a regular part of the shows [citation needed]
Though Kinguin departure was never announced, titular sponsor was gradually dropped from branding over the spring/summer of 2023. The last facebook post featuring Kinguin PTW name was from 26th March 2023, a cover photo change announcing Underground 14. Next graphics for the show however, did not feature Kinguin in logo and name

References:
probably last usage of Kinguin PTW.
https://www.facebook.com/PrimeTimeWrestlingPL/posts/961567858196579:961567858196579?__cft__[0]=AZWsVX8H2LroPGai-fbqxYGIWyW-R3jdc5_lfKpnM1arbqYH8qeNhWCBlq5BIZtD6_BktDajEihtNPTTjGnsbbKIPi-KKC5Tb3kap7CgVS-mfb_tEFOmpyX_1SicMtCRmJwZbRz5ZdL06kINaGJN3VumxmHzpztdzVHPtEJ4Y9huhkQXEGBSYlNiFHf-jh1szKA&__tn__=%2CO%2CP-R
PTW Revolucja announced [https://www.facebook.com/PrimeTimeWrestlingPL/posts/pfbid028PJVSfUZRm6FJL9UPTvPmFmFRc4eLAVD1zaDsxCvzbQJaj6dkLFiTied1dWCYzqVl?__cft__[0]=AZU7Ku2pOzaa2kmN43UIId_56yAntdJsxjKBBOtldkpkge_HKacBefARn5HoOzr3i2ofhi9wDIQ9SRyDf6i9ewMUTIYQtt9IW06CIdjOnigJcbo3YJPmfpuFhVRmhQyVx9gprwA1pp_m9xlhfb4TMQTy-w0a1TQT81Fd6yD8RolMmeVVwwb32AybCK5-xSXlTn8&__tn__=%2CO%2CP-R]
>

**Comment by iwulOG** [comment]
Add to history
Late 2023: crisis [to be reviewed and made more neutral maybe?]
In the aftermath of PTW #4 Mystery, the 5th show build-up was started. Initially planned for October 2023, the show was postponed indefinitely. During that time, multiple talents started to voice their frustration on social media. Eventually, Rafi Rarytas, Gabriel Queen, Justin Joy and Samson have all been removed from PTW's roster. During a [shoot interview](https://www.youtube.com/watch?v=0t8TTAVxQoE&t=3s) for "Wrestling Polska" YouTube channel, Samson stated that he "never earned a single penny" in PTW, that Underground shows are not paid appearances and only "big" (numbered) events are, with the promotor urging talent to take the "barter in training fee" instead. 
During the [live stream for YouTube supporters](https://www.youtube.com/watch?v=dmLHzSe92x0) Pawłowski confirmed the accusations, stating that barter was an option, but always voluntary. He also confirmed that PTW wrestlers are not officially contracted and their exclusivity is based on gentlemen's agreement. He emphasized that his goal is to make PTW a fully mainstream promotion, with wrestlers being able to earn their living just based on their PTW role, rather than proposed independent route with talent able to freelance. It was also announced that more roster cuts are to follow, especially after "season one" is finished.
In the beginning of 2024, Vic Golden was quietly removed from [PTW roster] (https://primetimewrestling.pl/roster/])

WWA acquisition:
Throughout 2023, Krampus, in addition to his in ring career in PTW, launched a wrestling promotion of his own, WWA (Wrestling World Austria).
The first set of tapings was [announced](https://www.facebook.com/ptwwrestlingdeutsch/posts/pfbid02xWH71TKXsqYsGpiZ1dXBPx3sJgj8GT2Fx2Mp5SNUzHTzd97zmPEoDoaRriPWV1tXl?__cft__[0]=AZXyzCEzvQvAUMtCa-GpvGBeA7mfAWj0UGwfITYUYaCYbgEOaXJUGCgPF5MJgx8BdGlQTrDB15b3T_yOBwBzC4fN6aGI497tD6_9uRf38kinEZayckQnS-vSZgdKh7lnaJUe0EwxbBHB8JzOTT_rwfO3fA1r7gZTOaRa2UPHSc0LKhHs8Rke3Af5bhhbJFiTwSs&__tn__=%2CO%2CP-R) for September 29th 2023, emanating from City Theater in Hallein, Austria. Among others, the show featured multiple talent from PTW. 
On December 4th 2023, both PTW and WWA announced that WWA is now becoming a part of PTW.
https://www.facebook.com/PrimeTimeWrestlingPL/posts/pfbid0Hfpa8ep1gi8X9NfmmkR3f5D8gVvZ4edWPTPVVvi3bZxuJRzFUywnD3n6AVzuvFDPl?__cft__[0]=AZXKDQAtGJ9qnsyLewSJw4D2iiOQigUAZRmfaR5A2x8PJZx8SejL3PV6rL17xhPxpIBfswo83Jdg-8hgUTUaVbXdViltCOfTRKJVK6DwrxFKX3v9sEl_tyCXV4pXMZ5zoDy6POvhdoGcTQz_Ny1gLhbfzp38vEdUxgtTzEv-F2KLgWni3vPLGGVeGgnhjxyiSPY&__tn__=%2CO%2CP-R
Initial name for the changed promotion was "PTW: WWA" (also stylized as "PTW presents: WWA"), but the promotion soon adopted "PTW German" as their [social media name] (https://www.facebook.com/ptwwrestlingdeutsch).

Add references:
[Official facebook fanpage](https://www.facebook.com/PrimeTimeWrestlingPL)
[YouTube channel](https://www.youtube.com/@PrimeTimeWrestlingpl)
[TrillerTV](https://www.trillertv.com/vl/p/prime-time-wrestling/)
[Roster](https://primetimewrestling.pl/roster/)

**Comment by k3rni** [comment]
Added in c3cd5aa. Leaving this open for more updates.

Need more links for the "multiple talents started to voice their frustration" - so far we have only Samson.

**Comment by k3rni** [comment]
PTW German added in 08863cd

**Comment by iwulOG** [comment]
> Added in [c3cd5aa](https://github.com/k3rni/teczki-polskiego-wrestlingu/commit/c3cd5aa047c5119dd8868efa0d1036cbc97caede). Leaving this open for more updates.
> 
> Need more links for the "multiple talents started to voice their frustration" - so far we have only Samson.
The hints were vague, as some of them started to make insider jokes about other federations and referencing other talent, contrary to how PTW wanted their wrestlers to handle social media.

Gabriel Queen started addressing talent gone from PTW: [Justin Joy](https://www.facebook.com/permalink.php?story_fbid=pfbid0SZJT7BbNDx961DvaJocj9UndesNgwc84CrgnPtbHQWM41G524imtecZyCnGPQX12l&id=100077204831290&__cft__[0]=AZWB7PN1xuwPGNIoaZSGFn8prLDLrNnCsTecgVt3PUw6vYMPapuHpUySpyrZDtwj0a31qKG1L2N_9p664hIe652qZw9G27m-C9biyPW944luEOe_eP4WQmbUnuS-7Fkdm2GQJsBGpsLsFi8tPU6lttE9GwOgB0qSFq5lDv2eW0eOuiMkOq9jaEEypW0m3r0kQlk&__tn__=%2CO%2CP-R)
, Jacob Crane (https://www.facebook.com/permalink.php?story_fbid=pfbid0aYa4xuBLN97Ggf5XtUD51PEJcu8yTLenpjUtndRggW1RWfmNATUxURNksUXTY9oKl&id=100077204831290&__cft__[0]=AZVRaWMun58z4iLDDrZDXE4QTLMmfdivSU-bIYmRsudk3RHNvzVToQmFQKDCkTAKg6FrzamgkGnmxCc7znkjhnSJAXFXeJjVL3pj6NVVH9FxpYOOyZR7keofCYJ87dn58ZNvF7WWR2DdoS4XQPdnFx0o1kbQWGkElGy0a8v3olZI_wQWQnWFgM6EUPM9QQelQ0I&__tn__=%2CO%2CP-R) and jokingly calling them out for a match outside PTW, [indirectly referencing PPW](https://www.facebook.com/permalink.php?story_fbid=pfbid02EBF7hRK2m8NuFecFW8FyXEUXCQtig7paf58vAu5WZzUVJExRJTePBcKaJyWR4QHNl&id=100077204831290&__cft__[0]=AZVqsYHIYs1-kWTtro6KCH4n6fbTkm41yL2lq3lGkBAtimL8G2cIzp15vVI09DJHCT7_fEgYif8bVHl1iRX2muICX1HT4N-jlh3NmzVpe5tcdQGpObp7O0SFpJ8OGfyd8BV_m87i1SwhhK43KuWd7f6civ4HmoVekjpBp23GyjD23xyKvoScv04GiiuPTGFMdms&__tn__=%2CO%2CP-R), reposted a photo with [Madman Charlie, affiliated with MZW and PPW](https://www.facebook.com/permalink.php?story_fbid=pfbid032X1muH6Ns5pk4Q6ZAH1iZGAyA2xAMqXR7T8sS57akeFV2K6YpB8Cm6o2wCRpfR2ul&id=100077204831290&__cft__[0]=AZXyEckWXxcqImyylZNQzfOk6_H4SJTu9b7_PHYdAfZ_DaNorReoofFk5ggb6XWq0NttVB7fGXipJnbU8Ca4d7G57yQTBcPSYINnC57h4QRq4YfQgNBoPvZmQ8BZ1dAWMoaE_RQyF3L4P89Oh-W77O6_ma6FjVOyb6yBhYKqjxr_6-rfKujpubxkiFSdfM9sg5c&__tn__=%2CO%2CP-R)

Justin Joy posted [Jacob Crane](https://www.facebook.com/justinjoy0/posts/pfbid0sQsi8Q6ShbvyBnJvvTKXUvjuVvipnqtJPxpnjBjczuic8VU9kLdeLLrJCPL3aELLl?__cft__[0]=AZUa3pOedL5DZsQDZ-INseqScOZTucrxq3xamus-Xs8HKFloP153cmVa0Mhts8Y38i9_bqaO75pH48eW3eCTozr00UxowWmtXvshmdSQX53yzd0FpxzjM4nc1MbOuihyUxRg6k9TRybac0k-lRH7p4XS13TFFwy5HLxz5hG_Xv5_5mplvc-4AHgChMcvh7FSHZo&__tn__=%2CO%2CP-R), who left PTW in disgrace back in 2022
On 20 December 2023, Justin provided a Q&A on Instagram and Facebook stories. Due to the time-limited nature of these posts, we only have a record in form of screenshots made by people who viewed it - most of them provided by Krzysztof Liger. [Thread in Wrestling Polska group](https://www.facebook.com/groups/wrestlingpolska/posts/7539753652724517/?__cft__[0]=AZURzOqFo1KmCpRnEb-SDH9TmmdaTG8CqWw6Ly1yp7JLDnqZbwi9cm12KhHhB9i0ucpMjrGqqnYWIWJIg1ZUpxRusHcEB-OpiOIH3z_7Jdu3bNYhbcbHxJ9_Ba9PCdNtcJngLhgBF31x7LCsHawLOhq_XhJKWfXGMbUMTwpFkifqqlP36vEflKsyCF-e4ep6JtI&__tn__=%2CO%2CP-R) Joy confirmed that after him giving a training to PPW wrestlers (a paid gig, without making any ties with the promotion), Pawłowski cut the ties with him and provided some shots on Pawłowski and PTW. 


![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/e7f2e1fb-70fe-4f1a-ac71-56bcae9dbdb6)
![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/cf405a34-6500-4bb5-90bc-985c2c49223f)
![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/b8c36ce1-5785-4e8f-9e8e-f8b929d442cb)
![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/6b79140e-6408-45d9-9be3-020bfb289d56)
![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/d24cc460-cc1c-46c3-a0c3-e338a360e8c4)
![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/e85c3687-cffe-4b99-9b98-6a210f1740f4)
![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/48bf9dd3-29a0-4927-b058-407ea67e870f)
![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/a6fb4199-f1ba-4483-bae3-6d1e5f8debf9)
![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/47c2869e-edd4-4c90-a591-9d824b234f7e)
![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/07e5721f-fc80-4109-981a-a922e1b0d7fb)
![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/a252bb03-e8b2-49c2-bbfd-f2bdf307f6cc)
![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/335119bf-60a9-4a59-906f-f49e75f976c0)
![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/3ee2b83b-1f46-4cca-b73a-0c55f6797995)
![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/b4559ebb-5905-40e0-8ead-521a1bc1acfb)
![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/cec8813d-26c4-48c0-be8c-68aeabccd0da)
![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/e0bbea0b-a2bb-438f-afdf-3408d5128048)
![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/9ce5cb30-8157-4597-868c-9600d9b0631c)
![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/10a1781d-cc50-45af-b472-17d4e0a15b34)
![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/2f73d088-5469-45a0-935a-54c28e2b6a6c)
![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/a5b2f88b-9b3a-413a-b8b8-c15ed6d5adf3)

![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/0569a373-7d58-49e0-b658-f3ada2d0f862)
![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/5388749b-46fb-4994-884b-159091d36cb2)

All the sources I could get, please check which can be useful to us

**Comment by iwulOG** [comment]
Add:

Rzeźniczek departs:
![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/d57f3c0d-ee7f-4446-8c8f-18258a47fac0)
Monday March 11th, "Rzeźnik" officially confirmed via Instagram Stories that he left PTW and that Pawłowski remains the sole leader of the organization. Breaking the kayfabe (recent storyline had him revealed as mastermind behind Bad Bones & Longman shenaningans), he wished Pawłowski best of luck, fondly recalling their time together in PTW.

**Comment by k3rni** [comment]
Justin's Q&A added in  d515ff3, but to Joy's article, not PTW.

**Comment by iwulOG** [comment]
**Which page:** `o/ptw.md`
**Your feedback:** 
<Add to "2023 crisis and departures"
Robert Star's departure went unannounced by the promotion, with his profile removed at some time between January and March 2024.
During his [interview ](https://www.youtube.com/watch?v=mRJrVjnAhyo) for Istota Wrestlingu YouTube channel, he confirmed his departure from PTW.

Remark:
some of the all time roster are marked in italics, while others are written ordinary way. I am unable to find any rule for this distinction, so we should either decide on some distinction (eg. inactive talent vs active talent) or just put them in normal font altogether>

**Comment by iwulOG** [comment]
Add to ebook:
The ebooks were short pdf documents (PTW Revolucja: 16 pages), including results from titular shows, photos and short narrative. It was apparent that they were not supposed to provide any content but rather serve as tickets for lottery.

**Comment by k3rni** [comment]
Added in 7087f262f996c6a5719dedf94bc8859e87226c4f. Closing for now, please reopen with new info.
