### ISSUE TITLE
Feedback on page: PTW 3 Legends

### ISSUE THREAD

**Issue by iwulOG** [k3rni/teczki-polskiego-wrestlingu#23]
Location: Hala MOSiR Bemowo, Warsaw
Personnel:
(commentary tbd)
Referees:
Sędzia Matek,
Sędzia Seweryn
Commentary:
Arek Paterek and Łukasz "Balik" Baliński - Polish
Lewis Costello and Santino - English
Paweł Boryss Borkowski and Andrzej Supron - special guest commentary for main event: 
Host, ring announcer, general manager: Arkadiusz "Pan" Pawłowski

Results:
Pure Gold (Vic Golden & Gabriel Queen) def. PAKA (Taras & Disco Pablo) - Tag Team Match
Marty Scurll def Primate
Myla Grace def. Xia Brookside, Diana Strong -  Triple Threat Match
Justin Joy def. Axel Fox - NO DQ Match
segment: Santino named a new co-owner of PTW. Bad Bones, who was released on previous show appears to beat him down, quickly escorted out of the arena by security.
Dawid Puncher Seńko def. Robert Star
Joe Hendry (c) def. Trenta Sevena - IMPACT Wrestling Digital Media Championship match
Segment: Post match, Kinguin mascot starts to circle around the ring erratically. Hendry reveals suspended Taxi Złotówa under the disguise. Złotówa begs Pawłowski to reinstate him, but gets dragged out of the ring by security. They escorted him out of the arena.
Sinister def. Starboy Nano Lopez - Last Man Standing Match
[Krampus interfered to align himself with Sinister]
Segment:
Scheduled match between Syriusz Dziedzic and Samson is cancelled due to Samson being not cleared to wrestle.
Syriusz Dziedzic and Wiktor Longman make their entrance. They cut a promo to brag about injuring Samson and declare Dziedzic a winner of scheduled match by countout. Samson makes his entrance, for a staredown with Longman. Longman makes his leave, Spartan lays Dziedzic out with Spartan Bomb.
Samuray Del Sol def. Sydal

Add references:
[Facebook post with results](https://www.facebook.com/PrimeTimeWrestlingPL/posts/pfbid0PERt7WVmHntfpDneYCHknL765cN2Ny8nFVam6gcHFAfKpppNze9Xd6fkRfJ4qmpql)
[Facebook post with match card](https://www.facebook.com/PrimeTimeWrestlingPL/posts/pfbid02u3Yzb8KGjS9vzS1Wt1c19dfL5CfyLYv1i2yXnG7QV4c56VAkfZpFBmNUiSfQkHR9l?__cft__[0]=AZWkU4csaeEmVTvezlc1HSPtyHCLUb3Lta7RdUyEWhFu44OEJnjx-ARDyPaH_TuMryGsptP83-Wg4xvh-3q_UH0ElkikLUpdi7YJ1lVxQSq9o3yx5z2umbXpUcaUamycS2z3UZVGkog98dSqJh_hTj5m&__tn__=%2CO%2CP-RP
[Full event on Fite/Triller](https://www.trillertv.com/watch/kinguin-ptw-underground-12/2pceo/)
[Full event on Youtube - free](https://www.youtube.com/watch?v=wuatGAUUfPI&t=2682s)

**Comment by k3rni** [comment]
Added in ea79f9a
