### ISSUE TITLE
Feedback on page: PTW X RyuCon 2022

### ISSUE THREAD

**Issue by iwulOG** [k3rni/teczki-polskiego-wrestlingu#26]
**Which page ?** `e/ptw/2022-07-31-ptw-x-ryucon.md`
**Your feedback:**
<Location: small hall of Tauron Arena , Stanisława Lema 7, Kraków
Personnel:
Referees: Sędzia Matek
Commentary: None
Host, ring announcer, general manager: Arkadiusz "Pan" Pawłowski

Trivia: Non-televised event, part of RyuCon manga convention

Results:

Axel Fox def. Justin Joy
Robert Star def. Syriusz Dziedzic
Sinister def. Starboy Nano Lopeza
Mike D. Vecchio def. Marcel "Marcelito" Budzianowski [Krampus was Vecchio's scheduled opponent but he failed to appear)
Pure Gold (Gabriel Queen & Vic Golden) def. Disco Pablo & Diana Strong
Dawid Puncher Seńko def. „Top Gun” Samson
Bad Bones def. Taras

Add references:
[Facebook post with results](https://www.facebook.com/PrimeTimeWrestlingPL/posts/pfbid02LqWm9jDNp18Bb4rMED5fpwZuQQXeRoWpDFC9vXVSa4BsbEGoBGY12Zd1xy6yHfq2l?__cft__[0]=AZUMgjJA08SKgBFp6gKLU_p5D14o0ppVURkZBhmWG8k_SnL9pzcSGjw1L8G-DByjERj4vHY4Ngu8kjo-VE7usRUbb3aWdow6d4uptezDyR5ArQc_EqSFJVY-bdc9Ef6aYboyZM8FK-zEY8cRVEA6CI9-idvulsv_QGn8yNU4fHC2mVqHQhIBivBz7U71x3b3Zpg&__tn__=%2CO%2CP-R)>

**Comment by k3rni** [comment]
Added in 8f96053
