### ISSUE TITLE
Feedback: PpW Ewenement

### ISSUE THREAD

**Issue by iwulOG** [k3rni/teczki-polskiego-wrestlingu#34]
**Which page:** `o/ppw.md`
**Your feedback:** 
<New ring:
Over the weekend 8th-10th March, PpW stars Biesiad Strong, Gustav Gryffin and Mr Z posted Insta-stories featuring them appearing in a sligthly larger ring than usual PpW one.

On March 11th, Mr Z (kayfabe executive producer of PpW, but also real-life member of PpW leadership) posted the photo of him and Andrzej Supron shaking hands, captioned "Two [guys] happy that the deal went through. Thank you Mr. Supron"

![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/d81b2331-50f1-43f8-aded-222dbef387b3)
![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/2fcea69d-add7-4666-89f3-2e927f381572)

![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/fd954f5f-896e-4717-8879-6e75b9ebb5fb)

issue to be put on hold until the official confirmation that handshake deal and new ring are indeed related
>

**Comment by k3rni** [comment]
Added in 02d0c2f. PpW themselves hinted at the new ring in recent Facebook posts, so it's fair to publsh now.
