### ISSUE TITLE
Feedback: PpW Ewenement Haze

### ISSUE THREAD

**Issue by iwulOG** [k3rni/teczki-polskiego-wrestlingu#38]
**Which page:** `e/ppw/2024-04-20-ppw-ewenement-haze.md`
**Your feedback:** 
<corrections + past tense
Ewenement Haze **was an** event by [PpW Ewenement](https://teczki-polskiego-wrestlingu.pages.dev/o/ppw/), taking place on Saturday April 20. The original venue was to be [Waldorffa 25](https://teczki-polskiego-wrestlingu.pages.dev/v/waldorffa25/), but due to miscommunication, it turned out that it's already booked for the night, and PpW had to find a replacement. The new venue is Praga Centrum, which is a music and event venue with a large outdoor garden, located in Warsaw's Praga district. According to Facebook posts, **the ring was to be be set outdoors, but plans changed and the show was held indoors after all**
The set featured a full stage and elevated ramp leading to the ring, with full size titantron, playing the videos for wrestlers' entrances.
The event's name refers to cannabis, whose many strains are often named "Something + Haze". This in turn, is a reference to the date, which, together with the number 420 are often associated with cannabis culture.

The foreign guests for this event were:

German wrestler Nick Schreier. In 2021, Nick, in his third ever match recorded on Cagematch, appeared for [MZW](https://teczki-polskiego-wrestlingu.pages.dev/o/mzw/) at [Project 8: Golden Road Finals](https://teczki-polskiego-wrestlingu.pages.dev/e/mzw/2021-08-14-mzw-project-8-golden-road-finals/).
Danish wrestler Benny Bacchus, who competes mostly in Denmark and Sweden
German wrestlers Joshua Amaru and Aytac Bahar, returning as a tag team. Their previous appearance was at [Mistrzowskie Rozdanie](https://teczki-polskiego-wrestlingu.pages.dev/e/ppw/2023-05-06-ppw-mistrzowskie-rozdanie/).
**Dominican wrestler Rambo, with 16 years of in-ring experience, mostly on German scene.** [skip Salsakid part, Rambo is his current ringname in Germany]'

please keep open, report to follow

>

**Comment by iwulOG** [comment]
Add show report

Ewenement Haze report
Commentary: 
Szymon Modzelewski,
Konrad "Joker" Grzesikiewicz
Host: "OG" Michael HT
Referees: Karol Górski, Kornel, Johnny Blade (as special guest referee for main event)

Results
Triple threat match:
Gustav Gryffin (w/Jakob Sigmarsson) def Nick Schreier, Samson
Tag team match:
Pure Gold (Gabriel Queen & Vic Golden) def. Baklava CLub (Aytac Bahar, Joshua Amaru)
Critical 420 Ladder Match for 20g of CBD marijuana: Goblin def. Benny Bacchus, Isnorr, Rafi
Bill Feager (c) def. "Real Deal" Mister Z to retain PpW Championship
Ultraviolent match for PpW European Ultraviolent Championship - Stanisław van Dobroniak (c) def. Alex Arthur (special guest referee: Johnny Blade)



Report
Show opens with host "OG" Michael HT entering the ring. He hypes up the crowd.
Referee Karol Górski is introduced and the announcements for first match start.

Triple Threat Match: Gustav Gryffin (w/Jakob Sigmarsson) v Nick Schreier v Samson
Gryffin makes his entrance accompanied by Sigmarsson to a chorus of boos and "get the f*** out" chants.

Nick Schreier hits the ring to a moderate pop.
Samson makes his entrance to a large pop. He's over with the crowd big time.
Match starts with both Samson and Schreier (babyfaces) forming an alliance against Gryffin. Sequence of double team moves from babyfaces and the crowd chants "This is awesome". With Gryffin laid out, Schreier and Samson fight 1 on 1.
Gryffin makes a comeback, fighting off both babyfaces. Match dynamic changes to every man for himself.
Samson with a top rope splash on Schreier, but Sigmarsson pulls Samson out of the ring and beats him down. Gryffin steals a pin and wins the match.

Winner: Gustav Gryffin

Tag Team Match: Pure Gold (Gabriel Queen & Vic Golden) v Baklava CLub (Aytac Bahar, Joshua Amaru)

Pure Gold make their entrance to a huge babyface reaction, crowd sings their "Best of both worlds" theme song.

Before the bell, we see eachteam climb the corners for crowd reactions. Pure Gold get huge pop, Baklava get booed.
Golden and Bahar start off with back and forth. Golden takes Aytac to his corner and tags in Gabriel Queen. Double team sequence on Bahar. Bahar tags Joshua Amaru in. Back and forth, Vic is tagged in, some double team moves on Joshua. Aytac hits Golden from outside the ropes, allowing Joshua to get the upperhand. Aytac tags back in, they dominate Vic Golden some more.
The crowd sings "Polska, biało-czerwoni" to encourage Golden. Referee is distracted and Baklava choke on Golden in their corner. Queen, trying to interfere, only makes matters worse, prolonging the distraction. Crowd is not happy with the referee. Golden tries to fight Baklava off and crawls back to his corner. He jumps for a hot tag, but Joshua drags Queen off the apron. Aytac uses the opportunity to lay Vic out once again with a clothesline. Gabriel Queen has enough and attempts to enter the ring, but referee holds him back once again - allowing the heels to double team Golden once again. Finally, Queen is tagged in, he lays both Baklava out with a sequence of moves. Pure Gold double team Aytac in their corner. They have Bahar in the middle of the ring, ready to hit their double team finisher, but Amaru drags Golden out of the ring. Baklava Club hit a 3D on Queen for a 2 count. All hell breaks loose, finally Pure Gold are alone with Aytac in the ring. They hit him with Golden shower (flying European uppercut + leg sweep combination) and Golden pins Aytac for a win.

Winners: Pure Gold (Gabriel Queen & Vic Golden)

Show of respect between two teams, they shake hands, Baklava raise victors' hands... only to lay them out with low-blows. They beat Pure Gold down and celebrate their "victory"

Critical 420 Ladder Match for 20g of CBD marijuana: Benny Bacchus v Isnorr v Rafi v Goblin

The trophy (20gram of CBD marijuana) is hung high above the ring. All 4 men square off, Rafi taunts everyone else. They beat him down. Isnorr stays in the ring with Rafi, while Goblin and Bacchus bring the ladder from outside. Bacchus climbs the ladder and tries to retrieve the trophy, but Goblin drops the ladder and the trophy accidentally falls off into the ring. In an unplanned development, babyfaces signal the referee, who retrieves the trophy, climbs the ladder and hangs it back. The bell rings once again and the match resumes.
Goblin and Bacchus each try to climb the ladder to grab the prize, but neither can get the upper hand. Isnorr drops them and now he's alone in the ring with Rafi. Goblin comes back with a kendo stick, Bacchus with another ladder. Goblin and Bacchus are now on opposite sides of the ladder. They realize they can jsut share the stash, hug and embrace. Just as Goblin is about to win the match, Rafi drags him off the ladder with an RKO. Rafi is alone on the ladder and nearly has the trophy in his hands, but Goblin and then Bacchus stop him. Goblin and Bacchus continue to work as a team against the other two. Isnorr assumes dominant position, lays babyfaces out. He sets up the table on the ramp, puts Goblin on it and bodyslams Benny on top of him - the table breaks. Rafi tries to sneak a win, but is stopped by Isnorr as well. Rafi makes a comeback, puts Isnorr through a horizontal ladder and attemps to climb the ladder. Bacchus makes a save, him and Goblin put Rafi through the table.
All four men climb the ladders and brawl, only to fall off them. Benny is alone on the ladder and has the match won, but sees Isnorr attempting to choke Goblin out with the ladder. He chooses loyalty over the win, saving Goblin with superman punch to Isnorr. Goblin and Rafi are last men standing, they climb the ladder and brawl. Goblin with a green mist to Rafi's face, he retrieves the trophy for a win. 

Winner: Goblin

Goblin and Benny share the stash, smoking it in the bucket, but before they can complete the ceremony, Gustav Gryffin appears out of nowhere and lays Goblin out with a chair, then bucket to the head for good measure. he steals the stash from Goblin and cuts a promo explaining himself. He wants revenge for the loss on Turbo OG and challenges Goblin for a match at the next show. The crowd urges Gustav to return the stash, so he rips the packet in half and throws the contents on the ground.

In comes Michael HT and starts in-ring charity auction for treatment of dog Scooby... with everyone still laid out. The picture of the dog (signed by PpW roster) is sold for 1200 zł. The show goes to a break.

Interviews, conducted by Joker.
Samson - he is not upset about his loss. He hints that his next match will be in singles competition against

Gustav Gryffin (w/Jakob Sigmarsson) - Gryffin says he does not care about morals, insults everyone and lays out his plan to become PPW Champion.
He claims that attack on Goblin was a sign of care - drugs and alcohol hold Goblin back and he can become a better wrestler without them. Gryffin tells the announcer to fuck off and leaves.

Pure Gold - they are happy about their win and not much concerned about Baklava laying them out (just small itch in the balls). Asked about future opponents, they would like to fight Gustav Gryffin and a partner of his choosing.

Isnorr - he confirms his plans to become PpW Champion. He thanks Biesiad Strong for igniting his passion towards hardcore wrestling and makes a challenge to Stanisław Van Dobroniak for PPW European Ultraviolent Championship

Rafi - he claims that he was cheated out of the win by bad referee, calls PpW "fucking backyard". He insults Goblin and is happy for Gryffin taking away the trophy - as long as Goblin does not have it.

Benny Bacchus - he's happy that Goblin won and wants to party after the show

Goblin - he comes in, barely walking, Joker holds him up. and helps him sit down. Asked about Gustav, he says "I hate him, he stole my weed". Goblin says that Turbo OG match was not really meaningful to him, but now, Gustav made the issue personal. Challenge for a match is accepted, Goblin wants it to be a hardcore match and for #1 contender to PPW Championship

Back from the break, Michael HT is in the ring. He announces referee Kornel who comes out from the stage to big ovation. Both competitors fight to the stage area with Mr Z taunting Biesiad and handing Rambo the scissors - but never directly interfering. Both brawl back to the ring and ringside area.

Rambo v Biesiad Strong [Biesiad's hair on the line, Biesiad has to win to earn a match against Mr Z]
Rambo enters the ring first to indifferent reaction. Mister Z appears on the stage and cuts a short promo putting Rambo over and promising that Biesiad's hair will be cut. He places a chair on the stage and takes a seat. Rambo introduces chairs to the match, chokes Biesiad with one and continues to pummel him. Biesiad eventually makes his comeback, drops Rambo between the ropes with enziguiri, 619, back to the ring with Buckshot lariat for a 2 count.
Biesiad lays Rambo out with chairshot to the head, places him at the table, set up in the corner. Attempt of spear through a table, counter, Rambo suplexes Biesiad breaking the table in half. Rambo throws a trash can into the ring and attemps to hit Besiad. Sequence of counters, Rambo gets a trash can to the face multiple times. Biesiad puts the can on laid out Rambo's body and hits a Swanton Bomb. Pinfall attempt broken up after Mister Z pulls Biesiad out. They get physical and distraction allows Rambo to make his comeback. Superplex on Biesiad, not enough for a 3 count. Z now enters the ring to get the job done. Rambo holds Biesiad down for Z to hit him with a can... but Biesiad dodges and Z lays his partner out instead. Biesiad disposes of Z, Rambo still laid out. Strong climbs the ropes again and hits Rambo with a Swanton for a 3 count.

Winner: Biesiad Strong

He grabs a mic for a short promo and challenges Mr Z to a match at next PpW show.

"Real Deal" Mister Z v Bill Feager (c) - PpW Championship

Mr Z makes his entrance to a chorus of boos and insults from the crowd. Next comes PpW Champion, Bill Feager, to a pop. Before Michael HT gets a chance to start formal introductions, Mr Z grabs the mic to cut a promo, putting down Feager as paper champion and putting himself over. He offers Feager a deal to lay down for him in the middle of a ring. He gives the mic to Feager for him to announce his decision... Feager puts the mic toward the audience who now chant "kill him". He refuses, ridiculing Mister Z's "deals"

They start a match in a competitive way, countering each other's moves. The crowd is having none of it, they only want violence and tables. Feager with Undertaker's legdrop to Z's head on the apron. He continues the assault, but Z makes a comeback, methodically working Feager's left knee, already slightly injured in Feager's previous match against Kuningas.
He channels Ric Flair with slow walk and elbow drop, right into figure four leg lock. Feager tries to brawl out of the hold, but fails. He drags himself and Z to the ropes, referee breaks the hold. Feager makes a comeback, HHH facebuster onto a knee, Z counters into full nelson, immediately countered into jawbreaker. They run the ropes, Feager with a Samoan Drop. 
He sets up Z for Pedigree, counter into enziguiri and Superkick for a 2 count.
Mr Z goes to the apron and attemps a slingshot top rope move, but Feager recovers. Kick to the gut, pedigree for 2 and a half count. 
Z is slowly recovering in the corner, in comes Feager with a sledgehammer. He attempts to hit Z with it, but he quickly dodges and counters into Big Deal (shining wizard variation) for a 2 count. While Feager recovers, Mr Z brings a chair to the ring. He drops Feager with chairshot to the back, then to the leg. Feager recovers and Z kills him with chairshot to the head.
Referee checks on laid out Feager while Z is slowly circling around. He picks Feager up only to drop him again with a chop. Z with slingshot clothesline and cocky pin scores him a 2 count.
Now, Mr Z slides a table into the ring. He works on Feager some more and sets the table up. A few hits, he tears Feager's shirt down and sets him up on the table. Feager somehow escapes the table, but Z quickly rams him into the other corner. Z with a hurricanrana from middle rope and now he puts Feager back on the table. As he climbs the top rope for signature moonsault, Feager stands up and powerbombs Z through the table. They both slowly recover on the ground and go into a kneeling brawl. They exchange blows and stand up, Feager with a Chokeslam for 2 count.
Feager prepares a chair, while kneeling Z slowly recovers, holding on to referee Kornel. Feager swings a chair, but Z pushes Kornel right into it. Monster heat for Mister Z, motionless referee falls out of the ring.
Z has Feager in figure 4 once again, out come Gustav Gryffin and Jakob Sigmarsson. Gustav with some punches to Feager who's still in the submission hold and the crowd goes wild. While Gryffin consults with Z, Sigmarsson prepares the table and slides it into the ring. Gryffin and Sigmarsson set up Feager on the table for Mister Z to moonsault him. They drag stunned referee back into the ring and he is busted open. Very slow count, kick out at 2. Now heels set up Feager, supposedly for triple powerbomb, but before Z picks him up, out of nowhere Biesiad appears. He buckshots Z and goes for a ground and pound. The crowd goes nuts. Heels get the upperhand once again, but out comes Goblin to even the odds. He brawls with Gryffin on the ringside. Biesiad and Sigmarsson brawl to the backstage area, throwing ladders around. Back to the ring, only referee and competitors stay. Feager attemps a Pedigree, but Z counters into a Pedigree of his own for a nearfall. They are both up, Z sets up Feager for a dropkick in the corner. He picks up Feager into powerbomb position but Feager counters with a sledgehammer to the head. Pedigree onto the chair for a 3 count - Feager retains.

Winner and still PpW Champion: Bill Feager

Feager celebrates in the ring with the championship and slowly makes his leave.
With him still on the ramp, Iron Maiden's "Run to the hills" starts playing. 
Jerry "Rich" Mandecky - PpW's major investor makes his entrance, accompanied by his bodyguard, Kapitan Bazooka. They pass Feager by and enter the ring, Mandecky turns to Z, still seatead in the corner. Mandecky is clearly disappointed in Z, he shakes his head at Z, looks at Bazooka and they both salute each other - it seems like he wants Bazooka to dispose of Mr Z. In the middle of the salute, Bazooka flips Mandecky off, kick to the gut, STUNNER!
Bazooka rips his security gear off and shows new set of gear underneath. He takes a chair, chairshot to Mandecky and elbow drop through a chair. Z is still looking on and leaves the ring. Bazooka prepares a black sack and puts it on Mandecky's head. Bazooka's theme music plays. He slowly drags Mandecky out of the arena and drives him away in his car. The crowd cheers, "PpW" chants all over.

Michael HT is back in the ring, he repeats the result of championship match. Ring crew slowly cleans the ring and we go for another break.

Ultraviolent match for PpW European Ultraviolent Championship - Stanisław van Dobroniak (c) v Alex Arthur
 
The challenger enters with a full set of items, wearing white PpW t-shirt.
Out comes the champion with a chair and two championship belts.

Referee Kornel is unable to work after being busted open in previous match, so Michael HT announces his replacement. Out comes Johnny Blade in a coat. He takes a mic to cut a promo. He says there is nobody crazy enough to officiate such a match - except for him. Johnny drops his coat and has a referee shirt underneath. He requests a deal, in exchange for officiating this match, Z is to lift his ban for Ultraviolent Championship titleshots. In comes a female member of ring crew and whispers something to HT's ear. Michael confirms that Z agreed to Blade's conditions. Dobroniak grabs a mic and he's having none of it. He insults PpW and promises to kill everyone in the ring and Z as well. Blade tells him to shut up and fight. They face off, but Johnny resumes order, he starts a match and the bell rings.

Arthur and Dobroniak lock up, Dobroniak pushes him into the corner. A quick sequence of moves, Arthur attempts a pinfall. Dobroniak slides out of the ring. Alex urges him back in, but Dobroniak is playing catch with him. They're both in the ring, Dobroniak starts stomping and pummeling Alex.
The crowd wants blood.
Dobroniak elbow drops Alexander and gets a pinfall, but Johnny Blade is counting very slowly. Dobroniak brings a chair into the ring and starts swinging on Arthur who's still on the mat. Then he uses trash can lids. He smashes a keyboard over Alexander's head. He disposes of the keyboard and now starts hitting Alexander with a crutch. Arthur is already busted open and his blood paints the ring. Dobroniak attempts a pinfall but once again Johnny counts in absurdly slow fashion. Dobroniak argues with referee and Arthur uses this chance to make his comeback with the chairshot to Dobroniak's head. One more chairshot, keyboard shot and another chairshot. Dobroniak is clearly in pain. Arthur hits him some more with additional item (seemingly a metal net) and attempts a pinfall. Now Johnny is counting at normal pace, but Dobroniak kicks out anyway. They're both on their feet, Arthur with a Cody Cutter from the corner. They brawl at ringside, both painted in blood.
The crowd is chanting "too much blood" now. Arthur drags Dobroniak back to the ring and sets up two chairs. He empties the box full of lighttubes. He seats himself and Dobroniak on each chair and they start exchanging blows. Arthur takes out a light tube and smashes it on Dobroniak's head. He responds with a tube shot of his own. They exchange the lighttube hits and Arthur gets the upper hand. He stands up, takes the chair he was seated at and drops Dobroniak with it. As Arthur prepares for his next attack, Dobroniak low blows him for a pinfall. Johnny counts even slower than before, a kickout. Stani gets in Johnny's face, Blade pushes him through Arthur's back onto the ground. Now Blade stops pretending to be impartial, they lay Dobroniak out with double clothesline. Blade with assisted top rope splash onto Dobroniak. Arthur climbs the top rope himself, but Dobroniak does Samoa Joe's "nope" walkout spot - Arthur misses. Dobroniak is furious, he starts attacking Blade with every item possible. Arthur is still laid out, Dobroniak shifts his focus to him and back to Johnny, Arthur uses the opportunity to attack Dobroniak, but he counters into a backbody drop. Tries to pin him, but now there is nobody to count the pin. Frustrated, he beats on Johnny some more, Arthur with a low blow. Arthur attempts to lift Dobroniak with an underhook, but does not have enough strength to do so. Dobroniak counters with a Polish hammer and pins Arthur, counting the pin by himself using motionless Johnny's hand. 1,2,3, The bell rings, Stanisław van Dobroniak retains

Winner and still PpW European Ultraviolent Champion: Stanisław Van Dobroniak
Dobroniak celebrates over laid out opponent and referee and makes his leave. Blade and Arthur recover, they make their leave to cheers from the crowd.

Michael HT is reluctant to enter the ring once again, but eventually decides to. He announces that Jerry Rich Mandecky has been driven away outside Warsaw by a masked person called Kapitan Bazooka. He announces that next show is going to be Ledwo Legalne 4.

Additional interviews, once again conducted by Joker:

Stanisław van Dobroniak:
He brags about his win and he's titlerun is nearly 600 days long. He's full of himself, calls himself a god, warlord, king

Biesiad Strong:
Joker asks him how many conspiracies he has thwarted, Strong jokingly remarks that all of them and one more. He promises to always stop conspiracies and do the same to Mister Z at the next show. Joker asks Biesiad to avenge Kornel, he asks if Kornel is part of any conspiracy. Joker denies, so Biesiad promises to avenge Kornel

Rambo:
He thinks Biesiad was lucky to win and blames his loss on Z's failed interference. He wants a rematch under No Holds Barred rules.

Johnny Blade:
Asked about the events from the championship match he refereed, Johnny does not care. He is happy about getting his title opportunity back and that's all that matters. He promises to beat Dobroniak for the title and leaves.

Mister Z:
Asked about his part in Rambo's loss, Z circles around the question. He says he couldn't stop himself from watching the match, he really wanted Biesiad to get bald. He will honor the deal - Biesiad won, so Z will face him. He blames his loss on Feager hitting Kornel with a chair, so he gives himself a rematch... But to honor the deal with Biesiad, he adds Biesiad to the match, making it a Triple threat. Biesiad v Mister Z v Feager for PpW Championship is on for the next show.
Z mentions the stipulation that made Biesiad unable to challenge for PpW Championship ever again... but now that Mandecky is gone, Z is the proper boss of PpW instead of executive producer, so he lifts the stipulation. Due to a contract between Mandecky and Z, if anything happens to Mandecky, Z is legally succeeding him as PpW owner.
Regarding Bazooka, he denies ordering him to attack Mandecky - Mandecky is treating everyone like dogs, so Bazooka just had enough.
Closing comment from Z - are you all happy that I don't have a belt? But I have PpW! He flips off the camera

Alex Arthur:
He feels like after a good fight. He likes the Ultraviolent belt, he showed he can hang with Dobroniak, so he wants a rematch down the line. Joker suggests a triple threat including Johnny and Arthur loves the idea. He leaves with a PpW chant toward camera

[Live on Youtube](https://www.youtube.com/watch?v=8u292TzKREA&t=16556s)
[PpW Facebook - results](https://www.facebook.com/OficjalnePPW/posts/pfbid02VDK1CTBvrB2rSQyHEB7jBkHE2BXPPxGnX5Dbkz8krDbJ9n9zMyiJwUXftAYVGPvol)

**Comment by k3rni** [comment]
Added in 5112aa0 with later updates.
