### ISSUE TITLE
ppw roster - Vic Golden

### ISSUE THREAD

**Issue by iwulOG** [k3rni/teczki-polskiego-wrestlingu#4]
add to page "PpW Ewenement":
All time roster
Vic Golden: 0 (saved Gabriel Queen from beatdown by Jacob Crane, later confirmed as part of Ewenement on PpW's facebook page)
source:
https://www.facebook.com/OficjalnePPW/posts/pfbid02bKzA

![ppw vic golden](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/fa09c7e2-4719-455b-a008-e0bb8bf0ec76)

**Comment by k3rni** [comment]
The All-Time roster is automatically generated from match cards (as is an individual talent's matchlist - with some issues when they used multiple names). It would count Vic if he was originally billed for the match, or if we added him as a cornerman/valet/manager to the Crane vs Queen match. But he was unannounced so we can't really do that.

However, adding a note about appearing in PpW and linking to the results post and the event page itself is :+1:, doing that instead.

**Comment by k3rni** [comment]
Expanded Vic's page in f033cba
