### ISSUE TITLE
Feedback: PTW#6: Total Blast From The Past

### ISSUE THREAD

**Issue by iwulOG** [k3rni/teczki-polskiego-wrestlingu#41]
**Which page:** `e/ptw/2024-05-11-ptw-6.md`
**Your feedback:** 
<"American wrestler Matt Sydal, most recently competing in All Elite Wrestling. This is his second appearance, after main eventing [PTW#3 Legends](https://tpwres.pl/e/ptw/2022-11-26-ptw-3-legends/). Originally he was also in the card for Gold Rush, but had to cancel at the last minute." actually 3rd appearance, he fought Nano Lopez at Blackout (and come out injured)
"American luchador Lince Dorado, best known for his time in WWE as one half of Lucha House Party (with Kalisto and later Gran Metalik). Previously at Gold Rush, he had a match against PJ Black." - not one half if there was 3 of them :) 

1st segment
"Pawłowski opens in the ring, this time without his signature knee drop, claiming to have a broken leg after the events of Gold Rush." - leave out the Gold Rush part. We have no grounds for suspicion that it's a work - the injury occurred some time between UG21 and PTW6 and was often used in non-wrestling context as well.

>

**Comment by iwulOG** [comment]
Add to build up:

As usual for PTW, the show was quite weakly promoted, relying on starpower and brand value. With PTW goodwill dwindling and lottery overshining the show's promotion, this turned out to be a bad move. The promotion was limited to announcements of next matches (text/photo posts on social media), DIY materials from competitors themselves (Diana/Heidi v Legia: https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.instagram.com%2Freel%2FC6sqouYMgzM%2F%3Figsh%3DMWozNDc3ejBhM2hwNg%253D%253D%26fbclid%3DIwZXh0bgNhZW0CMTAAAR17kW4vUOgIwA8axzUZouK5VecrYpthdy3geTftwzvBpV5DlVKdRMFV1Ng_aem_AQAHKCXBJwv9plrBsAXm968FU6wfG9j8DuW53Q8pQ263ObL53NfYAIut3JxmzzC-REP26uvW-jArdbR-rvz9Ol9q&h=AT0-iV39VZN1ig5R4Zn1s_psV-FIg9ZpdYyGtINGiely6Rwj3SoIB90pJpbYNzXqYTp8juxtB2JwhlIbndY8O-oDOawwYzqZ_uq1L-HQ-w-DNp5R75e50-j72iFDAI3wxg1RnFR2aZ_Xr_oLTj96&__tn__=-UK-R&c[0]=AT0BHDPtwhEvWNbUuuGFgvsd2jsQ6GCwbqXqaCO4JbYdpQfjh8rYO6FY2fH1BnJx5ZdyRFyXR5yt2iz_pD-8usXh0-PHppomac3ORLAjR1Aa1QBLAvl7MRWVt8SFSm4bybrk4LV9lPwnJiedsxGBBS5qcwRxmYr3m3uyxaRGnoo0sfzT7Cr6LF3p_uUg4Mf9YKdIu0aYmMvUyGUDaneQrx8GITA5m3r-_fURjNJEHrDgLmoLp9X4UGFkmbqiVWcOSFLk7ZZj5acBb58ABDI). 

As opposed to any other "big" PTW show, that featured long trailers based on show's theme, we never got one for this show. Instead we got a stock teaser (https://www.youtube.com/watch?v=tXoynFl_f1g), which one of the users in PTW fan group identified as available on stock website and used without any changes (https://l.facebook.com/l.php?u=https%3A%2F%2Fvideohive.net%2Fitem%2F2df-vhs-pack%2F36461819%3Ffbclid%3DIwZXh0bgNhZW0CMTAAAR17kW4vUOgIwA8axzUZouK5VecrYpthdy3geTftwzvBpV5DlVKdRMFV1Ng_aem_AQAHKCXBJwv9plrBsAXm968FU6wfG9j8DuW53Q8pQ263ObL53NfYAIut3JxmzzC-REP26uvW-jArdbR-rvz9Ol9q&h=AT2YphdWDyYZ7fXNnJ4GYKBOWvTQVQcB7k_2Di1liufdYSYMor2uUhdchyPDXxpfBOvmQjZ8uZR1Cs1cnxr41VaLr-ak61Hi_KLWl1KKe5raCmFYj4x_vUXX8TPZv7PUl35GoJcKvJCPEKqXWk-hkFNU3CLhAm_K&__tn__=R]-R&c[0]=AT1hM_YSAUqZSBhgoIx21UKcWTch22xR4CHX3FRIBhHw69qUPM_JXTblhtl1f-jesH8HZR5G7mLklsuDBemclE7qtNcCu1czTAYMqmA5hkT66GRjH7J3dmNAe_QaiF3XVccdrgG0Hva5tj8q1J6vz1Wm0RgEfilp0atHS36LPT9D9G6vrbinaEbCeXNBAd8aKdGpO2tjw_-SR5c45vPy91Uzq95hDpz8HEa64AEibblglBNTH1hj7tfY4t859jU)

Few days before the show, despite the apparent sell-out (as per ticket website kupbilecik), it became obvious that the arena wouldn't be filled. In came ticket giveaway by Stonoga (refer general article for PTW organization).
There was little info about the show's live transmission, right before the show it was revealed the show would be free on YouTube.

Reception and aftermath:

- the show was universally criticized within the community, with a near marathon of live streams from disappointed content creators:
Sunday: [Istota wrestlingu](https://www.youtube.com/watch?v=2dXtNWZ2QUg)
Monday: [Głos Wrestlingu](https://www.youtube.com/watch?v=YzM2mRommdc&pp=ygUQZ8WCb3Mgd3Jlc3RsaW5ndQ%3D%3D) followed by [Blaze](https://www.youtube.com/watch?v=juCA2TmWXLU)
- build-up for the show was abysmal and most of the matches even if good, had little reason for happening. This could be blamed on both booking and roster exits forcing the booker to pivot all the time
- in ring action itself was cited as fairly good. Some matches stood out (both triple threats, tag team titles, intergender), some were straight out bad or messed up due to booking
- confusing booking of Longman v Disco Pablo and main event Title match screwy finish (Dziedzic and Krampus laying both Babathunder and Puncher out, apparently to lay out a title challenge on Sinister's behalf) disappointed the fans, live and watching at home alike
- the atmosphere of the show was bad. Dead crowd, half-empty arena, most of the active fans located too sparsely to coordinate their chants. PpW wrestlers and friends section of the arena (dubbed "Stonoga sector" as they used a giveaway to get the tickets) stood out with coordinated chants and lively reaction. This gave some life to otherwise dead crowd and gained PpW additional free publicity after Thursday's Stonoga stunt
- live experience was problematic. Among problems cited, there was lack of facilities (drinks, food), barely existant merch section, overall confusion (no pointers for meet n greet), aggressive security. There seemed to be a lack of ring-crew, usual faces from PTW event staff were noticeably absent
- the aggressive promotion of lottery continued even after disappointing main event, with both competitors still laid out. 
- The [live show with lottery results](https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DDOgcwDhd53k%26fbclid%3DIwZXh0bgNhZW0CMTAAAR1hSVrXfEEcbC6ZQvkt3r7pfYhDgr7bOmjzEKb0q4mILzOayLpV5iq5j3I_aem_AQCqc_8iG2O6b_kUVsZ3v-UhPO9eVmW171ogyBj5J5k28sViGC9jDMQfxY9zl_aBCaku4enbymrPO7Jbv_P1m7Vv&h=AT0tlMv_qPDHALrCOwvXxwOx1IklAW98xmsTw-A58vuFWc_Vvfg_6t_xEtKAYJy4x6UXPKqYK25dBXRKzIwXAAMoXWG3Es1ijmKHMP5HK-OAP2d81YQ7DyNUVDhHGPHDbLykKEHmYvdhabZHdOfG&__tn__=-UK-R&c[0]=AT1Q_8rgmMbbVRyKlRAgNAYnLpAby9aOUQIxgyYAGpI29Lz_ekpMR7HgQtGGqkJtqDO7qozcgCevEpMk3uEOZtPqtDYYohAF5KVT8AaEUQC1qiQQ_xNGodz8M7oKbfI9cEH0Ao3hVoEE7LeKSgBz6LCxzkcQsHD_zZ8kF30X8UxG7_kFJfJZ4iIPrtQyLJFS_I6jHET2xB1s0I5Mz3jgaHH6AV6eIQasK5a9) next day was universally criticized. Despite PTW aiming to provide entertainment for whole family, this show included controversial guests (Stonoga once again, members of "Królowe Życia" cast), making distasteful, sexually-charged jokes on regular basis. The committee supposed to oversee the lottery was not present on camera, so it can only be assumed that they were actually present. The lottery failed to achieve its declared promotional goal - some prize winners, called live on the show had no idea who and why called them, did not recognize the names Pawłowski and PTW. The lottery final quickly went private on YouTube and materials started to disappear post show
- with lottery's failure, commercial and critical flop, concerns about potential end of PTW became louder than ever.

**Comment by k3rni** [comment]
Added in 399d43e
