### ISSUE TITLE
Feedback: PTW#2: BlackOut

### ISSUE THREAD

**Issue by iwulOG** [k3rni/teczki-polskiego-wrestlingu#46]
**Which page:** `e/ptw/2022-02-19-ptw-2-blackout.md`
**Your feedback:** 
<add more detail

Blackout

Build:
contract signing before the show - 18 Feb 2022 (https://www.youtube.com/watch?v=SPd2OXsk9cM)
Featured the competitors from Blackout matches, signing the contracts for their respective matches... but not before cutting the promo on each other. While some of the segments were limited to promo/interview (with Pawłowski translating whenever someone spoko English), others got physical.
The final segment was supposed to feature a signing for main event between Chris Adonis (previously featured under his WWE name - Chris Masters) and Nick Aldis (fallout from Revolucja where Adonis cost Aldis a match against Gracjan Korpo). Adonis was absent, so Aldis hyped the match by himself and signed the contract

Location: Hala MORiS Chorzów
Personnel:
Commentary: Arek Paterek, Łukasz "Balik" Baliński
English commentary: Dave Bradshaw, Santino
Referees: Seweryn, Matek

Show opens with Pawłowski and Rzeźniczek, being interviewed by journalist. They hype up the show and we get to video packages. Then we get some more hype from commentary
The show starts with a countdown on the big screen. Bring me The Horizon's "Throne" plays and owner, Pan Pawłowski, makes full entrance, complete with high fives to fans and double kneedrop in the middle of a ring. He cuts a usual promo hyping up the crowd for amazing show tonight.
He announces Santino, who makes his entrance. They hype the show together some more. Santino takes his spot as English commentator.

Pawłowski announces the opening match. Video package for Jacob Crane v Tristan Archer plays.
Jacob Crane vs Tristan Archer
Crane, billed from "central Europe" as he renounced his Polish identity, makes his entrance first, followed by Archer. After the bell, they start with usual lock up and quickly pick up the pace, with Crane going fast-paced with strong style, as opposed to Archer's power oriented style. Heelish antics allow Crane to keep Archer in check, but he eventually makes a come back with suicide dive, lariat in a forearm and a falcon arrow for a near-fall. Crane misses a top rope move, Archer picks him up into piledriver position and hits a variation of backstabber. After a match barely 10 minutes long, Archer wins. 
Winner: Tristan Archer
This marks Crane's final appearance on PTW numbered show (followed by a few Undergrounds) and Archer's only PTW match to date.

Up next, triple threat match.
Jonny Storm and Justin Joy make their entrances. Special video package for Axel Fox plays and he gets a more hyped announcement.

Joy is a heel in the match, a lot of bad blood between him and Fox. After some early alliances, the match gets into "every man for himself" dynamic. The crowd is firmly behind Fox. After tower powerbomb/superplex spot, all competitors are laid out. Storm hits his finisher on Fox, attempts a pinfall, but down from top rope comes Joy with elbow drop to Fox (Storm dodges last second). After some scuffle, Joy low-blows Storm and pins Fox for a win.
Post-match, Justin Joy beats on Fox some more. Low-blowed Storm slowly recovers and finally makes a save. They chase Joy off to ringside. Joy wants his music to be played, but Pawłowski says Fox deserves his music to be played as the one standing tall.

Next match is Nano Lopez v Matt Sydal. Hype video plays up Lopez idolizing Sydal and this being his dream match. 
Starboy makes his entrance first to a moderate pop.
They trade submission moves, armdrags and Lopez clearly can't keep up the pace. The match gets more grounded, Sydal works Nano's leg. They get into back and forth, Sydal wins with Lightning Spiral
Winner: Matt Sydal
Post-match, both shake hands and hug.
Trivia: this was Sydal's last match before confirming that he's out of AEW ring with a dislocated knee. It's possible that the injury occured here, as Sydal noticably slowed down in the middle of a match and did not use top rope finisher.

Bad Bones v Axel Tischer (c) - GWF Championship
Bad Bones makes his entrance first wearing glasses and bandana channeling his idol, Randy Savage. Pawłowski calls him "Randy Savage after a year in Poland" and Bones doesn't like it. Pawłowski starts to announce the champion, but Bones cuts him off with a shove. Referee separates them and Pawłowski finishes the announcements. Tischer makes his entrance, with a live performance of his theme song's singer Dave Grunewald.
The match starts with both wrestlers playing with the crowd. Crowd is firmly behind Tischer and Bad Bones gets "Bad Bones sucks" chants. They start with technical wrestling on the ground, trading holds. They both stand up and Bones starts to dominate Tischer with some strikes. They trade running offense with Tischer getting the upper hand. Axeman goes to the apron, gets back to the ring with slingshot roll on the top rope and hits Bones with a running cutter. They trade more offense with no man gaining an upperhand. They run the ropes, Bones sets himself up for backbody drop, but Tischer counters with a kick to the head. He runs at Bones for some high impact offense but he counters with Orton-esque snap scoopslam. Now Bones punishes Axeman with strikes, slams and a seated choke. Tischer gets on his feet and starts to break free. Bones runs at him in the corner but the champion dodges. They are both laid out. Both slowly get to their feet and start a standing slugfest sequence, with Tischer getting "yay" and Bones "boo" reaction. Now Tischer is dominant, He makes a combo of offense on Bones and climbs the top rope for a flying superman punch on now standing Bones. He hits his finisher (a twisting vertical suplex) for a nearfall and "it was 3" chants from the crowd. Bones counter his top rope move into a lungblower and hits a Shadow driver (piledriver) for a pinfall - but Tischer breaks a count with foot on the rope. "This is awesome" chants are loud now. Bad Bones climbs the rope and hits a flying senton, but Tischer dodges. Bones is in pain, Axel Tischer capitalizes with a variation of powerbomb. 1,2,3, he retains GWF championship. 
Winner and still GWF champion - Axel Tischer
Post-match, Tischer celebrates some in the ring and slowly leaves as his music plays. Bones is visibly angry for his loss, bullying ringside staff and throwing chairs at Pawłowski in the ring. As Bones makes his leave, Pawłowski jokingly no-sells the situation and takes the show to a break. 

During the break, we have ringside interviews with influencer guests, discussing if wrestling is real or staged and throwing jokes around.

Back from the break, Pawłowski welcomes everyone again and announces the next match.
Syriusz Dziedzic, Dawid "Puncher" Seńko and Sinister vs Paka (Boro, Disco Pablo, Taras)
Syriusz Dziedzic (announced as "Future legend of Polish pro wrestling), Dawid "Puncher" Seńko and Sinister make their entrance for a heel team.
Paka makes their entrance as a team. Disco Pablo enters the stage to his theme, then Taras joins with his own theme playing. Eventually Boro joins them and they enter together to Boro's theme. They enter the ring and heels make their leave.
Sinister and Taras officially start the match, Taras dominates Sinister and makes a tag to Disco Pablo. Double team move on Sinister. Quick tags in the corner and all three dominate Sinister some more. Now, Pablo sets Sinister up for a fireman's carry move, but he's too close to other team's corner. Dziedzic capitalizes with a blind tag, enters the ring and saves Sinister. Double team moves on Pablo and Dziedzic continues to pummel him.
Pablo makes a hot tag to Boro, Dziedzic tags Sinister back in. Heels get an upperhand on Boro, attacking him at ringside. Rest of Paka steps in to make sure that heels don't fight Boro together. Boro and Puncher in heel team's corner, they choke Boro while Dziedzic distracts the ref. Boro makes another hot tag and Taras steps in with a house of fire on now tagged-in Puncher from opposite team. The order is lost, members of both teams join in, Paka hits a simultaneous suplex on each of the opponents. Ring is cleared, Taras hits a cannonball and tags Pablo in. Puncher is a legal man, he hits Wylew (super man punch) on Pablo, but meanwhile Dziedzic taagged back in. While referee tries to count a pin for Puncher, Dziedzic makes it known he tagged in so the pin is cancelled. He wants to be the one who scores a win for his team. He pins Pablo, but the commotion allowed Pablo to recover - 2 count. Frustrated Puncher lays out Dziedzic, boro hits Dobry Podryw (Olympic slam) on Puncher who falls out of the ring. Legal man Pablo hits Koniec imprezy (Blue Thunder Bomb) on now-legal Dziedzic to win a match for Paka. 

Winners: Paka (Boro, Disco Pablo, Taras)

Babyface team celebrates, high-fiving ringside staff and fans.
Puncher is back in the ring and cuts off Pawłowski's announcement of match results. He takes a mic for a short promo. He doesn't take the responsibility for the loss, blaming his teammates. He starts insulting all the VIPs, saying they are walking advertisements. One of the influencers, Maciej "Człowiek Warga" Dąbrowski, steps into the ring to confront Puncher. There seems to be a visible misunderstanding with security, as a security staff member first holds Warga back aggresively and then follows him all the way into the ring.
Puncher buries Warga verbally, who responds calling him a "third, aborted, Tyburski" (a dig at Tyburski twins, influencers who share physical resemblance with Puncher). Puncher is livid, but Warga continues with cheap insults. They continue trading shots and Puncher extends an offer to Warga - he either leaves or Puncher takes him out of the ring himself. He shows his butt to Puncher who is furious and jumps at Dąbrowski... only to be cut off by security who escort him out of the arena. Dąbrowski hides under the ring apron and only leaves when he's sure Puncher is gone.

Pawłowski goes to announcements for the next match. 
Marty Scurll v Krampus
Marty Scurll makes his trademark entrance with plague doctor mask and an umbrella. The crowd is clearly on his side, some "Villain section" signs present in the crowd.
Krampus makes his entrance, first in what would become a lengthy relationship with PTW. 
Referee checks both performers and starts the match. They go back and forth with their offense, the crowd reacts mildly. While Krampus throws Marty around, Villain goes at him with strikes. They continue to fight at rigside, superkick and Marty drags Krampus back in. He works Krampus' left leg with strikes and submission moves. Marty fith a figure four leg-lock, Krampus tries to fight through. He rolls and inverts the hold, Marty has to hold the rope to break the hold. Krampus with a suplex, but he has troubles with leg. Powerbomb attempt is cut off by Villain with a chop block to injured leg. They trade more offense, now crowd is 50-50. Scurll with a superplex to Krampus for a 2-count. Scurll grabs the umbrella and goes at Krampus, but ref is quick enough to takes it away. Krampus capitalizes and hits Scurll with his finisher (fireman's carry neckbreaker) for a win

Winner: Krampus

 Gabriel Queen w/Taxi Złotówa v Joe Hendry
Gabriel Queen pre-tape promo, he talks about himself and his new tag team partner.
Gabriel Queen makes his entrance accompanied by Taxi Złotówa. Złotówa is clad in Wolf group gear(security company for PTW events) to sell the angle where he tries to bypass his suspension with any loophole possible. He cuts a promo, putting over his friendship with Queen. He promises to watch over Queen forever and protect him from "Thieri Henry"... Queen corrects him it's "Joe Hendry". They hug and Złotówa leaves the ring.
Pawłowski goes to announcing Queen's opponent. Hendry's usual music video plays - it's a cover of Kings of Leon - Sex is on fire, where he sets a Taxi on fire. Złotówa and Queen are livid in the ring.
Hendry makes his full entrance to his now topping the charts theme song.
Złotówa gives Gabriel some hype from the apron, the bell rings and Gabriel charges at Hendry, who quickly lifts him up. He runs some with Queen in the air and throws him with a chokeslam of sorts. Now Hendry with a vertical suplex and fireman's carry. Queen escapes and quickly rolls out of the ring. He slides back to the ring and tries to sneak one on Hendry, but he counters, holds him up and into fireman's carry position and front throw. Queen falls out of the ring and Hendry chases him around. He's back in the ring first and for some reason referee holds him back, Złotówa capitalizes with a series of attacks on Hendry at ringside. Hendry finally gets back into the ring, Queen decks him. Now he assumes dominance with some corner moves and a pinfall for 1 count. They brawl some and Złotówa sneaks into the ring. Despite being clearly in referee's vision, he sneaks a chopblock on unaware Hendry - and the referee no-sells the interference. Złotówa leaves the ring, Queen with a guillotine choke on his opponent. Hendry makes a comeback with some lariats and a cutter, referee checks on Queen in the corner. Now Złotówa interferes again, laying Hendry out with a low blow. Queen pins but scores only a 2-count. Złotówa attempts to help Queen once again, but miscommunication results in him accidentally pushing Queen into the corner, allowing Hendry to scoop them both up for a fallaway slam. He powerbombs Queen for a 3 count
Winner: Joe Hendry

Hendry celebrates and leaves the ring, Złotówa comes in to check on Queen. Queen motions for a mic, takes it and screams like a little girl. He blames Złotówa for his loss and crowd joins in with "all your fault" chants. He verbally buries Złotówa and fires him from manager job. Złotówa is livid and picks him up for a Taxi Driver (Michinoku driver with additional swinging), he hits it, pins Queen and counts to 3... but there was no match going on. Arczi Czajka's music plays and he runs into the ring to get revenge for Złotówa hitting him with Taxi Driver at previous show (Underground). Złotówa attempts another Taxi Driver but Czajka dropkicks him out of the ring. Złotówa is escorted out while Arczi celebrates.
Czajka grabs a mic and says he's there because he couldn't miss such a great party. He says he's now taking an Uber to Bydgoszcz - where his current nemesis, Remo, resides.
He would not come back from there until his surprise return in Gold Rush Rumble nearly two years later.

Pawłowski goes to the introductions for tonight's main event.

Chris Adonis v Nick Aldis
After his initial appearance under WWE ringname Chris Masters at Revolucja, tonight he enters as Chris Adonis, his indy gimmick.
Aldis makes his entrance second, high fiving the fans and to the strong pop.
The bell rings, both pose some in the corners to gauge crowd's reactions, Adonis gets strong heel heat. They start off technical, trading locks. Adonis keeps Aldis in headlock, only releasing the hold a few times to run the ropes for a shoulder block. Missed elbow drop on Aldis who makes a comeback, now taking Adonis on the ground for a headlock of his own. They stand up, Adonis pushes him into the corner and regains advantage with some corner strikes. They run the ropes, Aldis decks Adonis with a Thesz Press and strikes him some more. Adonis in the corner, corner chop from Aldis, next corner, next chop, Aldis grabs the turnbuckle for a 10-count punch, but Adonis bites him before the 10th punch. Adonis leaves to takes a time out at ringside, referee counts. He takes his time, breaks the count and leaves again. Adonis drags Aldis to ringside and they brawl, Irish whip from Adonis into steeel guardrail. Adonis pushes Aldis into the apron, breaks the count and throws him back in the ring. Double axe handle from middle rope on Aldis. Adonis punishes Aldis some more with strikes and pushes him onto middle rope, runs the ropes for a seated senton. Pinfall attempt, headlock on seated Aldis who breaks free. Adonis with a backbreaker, working Aldis' back. Adonis takes his time to taunt Santino who's on commentary and now with a knee into seated Aldis' back submission. Aldis breaks the hold and tries to make his comeback, steps back up, runs the rope and is cut off by elbow from Adonis. He climbs middle rope once again, but Aldis runs at him with punches. Aldis sets Adonis in position, superplex! They're both back to their feet and trade strikes. Adonis with upperhand and attempts a Masterlock, but Aldis quickly breaks free. Now a series of running lariats, until Adonis is laid out. Aldis runs at Adonis in the corner, Adonis counters with an elbow, runs at Aldis who counters into a powerslam. Pinfall attempt to no avail, Aldis quickly takes it to the top rope. Before he can move, Adonis dodges and charges at him, Aldis with a jump to his legs. Adonis capitalizes with a spinebuster. Nearfall, frustrated Adonis argues with ref about the count. He motions for a Polish hammer from the corner and hits it, but second one is countered. Aldis with fireman's carry and samoan drop for a 2 count. He's bleeding from his mouth now. Another samoan drop attempt, now Adonis breaks free and pushes Aldis in the corner, accidentally laying out the referee, who falls out of the ring. Adonis quickly capitalizes with a low-blow, rolls Adonis up for a 3 count, but there is no referee to count. Santino checks on laid out Matek, but Adonis shoves him away and pushes unconscious referee into the ring. Santino is having none of it, he enters the ring and wears his signature glove, to hit Adonis with Cobra. Aldis climbs top rope for a flying elbow and hits it for a 3 count.

Winner: Nick Aldis
Aldis celebrates some in the ring and leaves, high fiving the fans. Pawłowski gets back into the ring, he thanks the fans, thanks titular sponsor and asks the crowd to chant for Kinguin. He continues the usual clapping for each sponsor routine, when WrestleFans is mentioned, he also thanks Paweł Boryss Borkowski (its creator) and teases his future appearance as guest commentator. That promise would materialize multiple times in the future.
Pawłowski plugs next shows - unnamed yet 3rd show and Underground in March and says goodbye to the fans. 
Camera moves to commentary, who talk some about the show, they say goodbye to the viewers and the transmission ends.

References:
[Full show on Youtube - free](https://www.youtube.com/watch?v=HYkTJlRNHAw)
[Sydal's knee injury tweet](https://twitter.com/MattSydal?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1505234895110651913%7Ctwgr%5E8afbf797e22599104cae8c8ba2bff2084245e6b6%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fwww.f4wonline.com%2Fnews%2Faew%2Faew-matt-sydal-suffers-dislocated-knee%2F)
[Show's trailer](https://www.youtube.com/watch?v=CWHcYux4reg)
[Sydal's knee injury news](https://www.f4wonline.com/news/aew/aew-matt-sydal-suffers-dislocated-knee/)
[Contract signing - free on Youtube](https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DSPd2OXsk9cM%26fbclid%3DIwZXh0bgNhZW0CMTAAAR0G61_wI7UfBr_z0xK0x-KXmSZEXegfTyys5VlsdwtvRd-_GvMbSsMtN1g_aem_AY04cUOvUK5ri1VgCKT7J1QijD42ome0D9FzTZsbmlG9R5uRZFqxg-HBRzZ5yuKznVO4s2QUbriJ0J0QZEFGE0_3&h=AT3DcC868Xb5MVlZlrtq-5HJKt1xDIE31BBbP6NTpsZnSgu357QobnMWwv6hWXiw0UPQI9qE7WJz22vQamEfLoyt13nsr3g9_UsVK2mjIVVipcNsepBqNbTxboSoWmPMgmTkcwlsBFAlfyMOtWc8&__tn__=R]-R&c[0]=AT2WAc2zxpfx6AIRbC8zK6f3UBVloyUQIlZavEvj4rkThyWSR4cF-Tugpg63Sfdle0jZzNwTyORnIdshOkNyQ4fBUAovJ7TSq7MUv2MWCFIIbpaag7WrBO89CJ0N8BbzQb9j1AoAhsyFOHUDp-bXU_2cmhutXQNTvB3p6_mHn2mh0lAmc8Y1M64NQU3czWlNiVcpfAoyZ9G8KCo90UvhbTg9SA9Oqk1k5-99J3Or5dJ9JdPQqA)
[Dave Grunewald singing Tischer's song](https://www.youtube.com/watch?v=-Es6BY6NuuE)>

**Comment by k3rni** [comment]
Merged in #49
