### ISSUE TITLE
Feedback on page: PpW Miasto Bezprawia

### ISSUE THREAD

**Issue by iwulOG** [k3rni/teczki-polskiego-wrestlingu#5]
**Which page ?** `e/2024-02-10-ppw-miasto-bezprawia.md`
**Your feedback:**
<
1. add to references:
Facebook recap post (https://www.facebook.com/OficjalnePPW/posts/pfbid02bKzAWkrtkZrgDNzm2dqBsveZge9LyMY9HHJGb1kY2n29RXNAYuebgopmsS63eKhPl?__cft__[0]=AZWC8_dU2uAE7rpIFBh6cdjMlzqlQWaVbrdrunxcFFw5DN-L8z6Ac41joY0tjTjL0EoaSxchQcAnNxE5hpl-GLqZTICXoZ16FuwYmm3A4UFWDN_2jlTPLRvYISzFCgugEeDa5rrge-n3Q-lUfwb82ZxmoRdnrDSEpeIjUQ77lbPU6fVNCZ5314GpaZNXU5DmByA&__tn__=%2CO%2CP-R)
Botchamania reel on MBM's table botch and repetition: https://www.facebook.com/reel/921293886126124
2. Add to Goblin v MBM. "The botch and repetition made it to Botchamania's facebook page"
3.Fill in the gap in Ricardo v Mr Z description: "Mr Z wins the match to become a #1 contender"
4. Finish the description of Feager v Steve Kuningas. "Feager wins with the Pedigree to become a new PpW Champion. He gets into an emotional celebration with the audience afterwards, to finish the show>
5. Grammar:
"Based on the poster, the show will [change to "would"] also feature [Jacob Crane](https://teczki-polskiego-wrestlingu.pages.dev/w/jacob-crane/), [Mister Z](https://teczki-polskiego-wrestlingu.pages.dev/w/mister-z/), [Goblin](https://teczki-polskiego-wrestlingu.pages.dev/w/goblin/), [Ricardo Diesel](https://teczki-polskiego-wrestlingu.pages.dev/w/ricardo-diesel/), [Gustav Gryffin](https://teczki-polskiego-wrestlingu.pages.dev/w/gustav-gryffin/), [Johnny Blade](https://teczki-polskiego-wrestlingu.pages.dev/w/johnny-blade/), [Biesiad](https://teczki-polskiego-wrestlingu.pages.dev/w/biesiad/), Chris X, [Isnorr](https://teczki-polskiego-wrestlingu.pages.dev/w/isnorr/), Asara and Gabriel Queen and Samson as noted above"

**Comment by k3rni** [comment]
Added in cf5e37d
