### ISSUE TITLE
Feedback: PpW Turbo OG

### ISSUE THREAD

**Issue by GumballHomar** [k3rni/teczki-polskiego-wrestlingu#54]
**Which page:** `e/ppw/2023-12-08-ppw-turbo-og.md`
**Your feedback:** 
<Wrong results - Isnorr defeated Biesiad by pinfall>

**Comment by k3rni** [comment]
Indeed! Even the [linked source](https://www.facebook.com/OficjalnePPW/posts/pfbid0yBtcocDLLf2mU2ox3FyYjXK7Qem9hws3rW58juZudTEEXjyJG2vCDrQTrWKkywKZl) says so, and we still had it wrong.

Fixed in 058c965. Thank you for your contribution!
