### ISSUE TITLE
Feedback: Do Or Die Wrestling

### ISSUE THREAD

**Issue by M3n747** [k3rni/teczki-polskiego-wrestlingu#55]
**Which page:** `o/ddw.md`
**Your feedback:** 
Po DDW House Show #2 było jeszcze DDW @ Baltikon 2015, 24.07.2015 w Sopocie w Zespole Szkół nr 1 im. Marii Skłodowskiej-Curie:

https://konwenty-poludniowe.pl/konwenty/kalendarz/205-baltikon-2015
https://wrestlefans.pl/forum/viewtopic.php?p=418906&sid=dbea7aa5e876e712bf24681029b6c4fd#p418906
https://www.facebook.com/DoOrDieWrestling/posts/pfbid0E8BmaAwYKP8EZ14tZfPpwMGgwR1HtyjqD5esNQPCa4fr44gqYH691TYx9QC5tyLnl
https://www.facebook.com/Baltikon/posts/pfbid02XnBeM3ALvf1brgkJLWwWs4DUjXq7A2CLG23AyQyRHNtHcoMgPiU2zHPLwu3nFJml

Z tego co mi wiadomo, to to właśnie było ostatnie wydarzenie zorganizowane przez DDW. Niestety nie udało mi się znaleźć karty, ani tym bardziej wyników, więc na CM ta gala jest nieobecna.

**Comment by k3rni** [comment]
Link to preview https://f055a909.teczki-polskiego-wrestlingu.pages.dev/e/ddw/2015-07-24-ddw-baltikon/, additional feedback welcome. Will ship tomorrow if nothing needs fixing.

Dzięki za te znalezisko. Dokładnie to jest celem teczek - skupić się na polskim wrestlingu i dokumentować jak najwięcej.
