### ISSUE TITLE
Feedback: PPW Kiedyś Będzie Lepiej

### ISSUE THREAD

**Issue by M3n747** [k3rni/teczki-polskiego-wrestlingu#59]
**Which page:** `e/ppw/2019-07-19-ppw-kiedys-bedzie-lepiej.md`
**Your feedback:** 
Feager miał być w tej walce, ale nie był:
https://youtu.be/DOAeXjrpmlg?si=56QNh1AoTHGpUFam&t=2144

Czwartym przeciwnikiem był Jeff:
https://youtu.be/DOAeXjrpmlg?si=IXY9l6jse00TUJt0&t=2216

...i to on zwyciężył pojedynek:
https://youtu.be/DOAeXjrpmlg?si=u0bIPUZRjmmMSHtA&t=2968

**Comment by k3rni** [comment]
Added Jeff and fixed the result in 6079a71. Also added a note (visible only when results are displayed) stating that Feager no-showed.
