### ISSUE TITLE
Feedback: Prime Time Wrestling

### ISSUE THREAD

**Issue by M3n747** [k3rni/teczki-polskiego-wrestlingu#61]
**Which page:** `o/ptw.md`
**Your feedback:** 
"apparent disinterest" -> "apparent lack of interest"

"Disinterested" nie oznacza tego samego, co "uninterested", a mylenie jednego z drugim to powszechny błąd. 
https://brians.wsu.edu/2016/05/25/disinterested-uninterested/

**Comment by k3rni** [comment]
37520fc
