### ISSUE TITLE
Feedback: Prime Time Wrestling

### ISSUE THREAD

**Issue by M3n747** [k3rni/teczki-polskiego-wrestlingu#62]
**Which page:** `o/ptw.md`
**Your feedback:** 
Warto by może dodać, że w ostatnim czasie (jakoś dzisiaj albo wczoraj) z oficjalnej strony PTW zniknęła zakładka 'Roster':
https://i.imgur.com/RzfTBBu.png

**Comment by M3n747** [comment]
(Dobra, już po wysłaniu powyższego zauważyłem, że jest o tym informacja w nawiasie niżej na stronie. Chociaż może jakieś zdanie w treści artykułu by nie zaszkodziło.)

**Comment by k3rni** [comment]
Sam zauważyłem kilka minut wcześniej. Poza nawiasem przy linku do rosteru, jest też jedno zdanie w sekcji "More high-profile exits".  Natomiast mam archiwalną wersję (w postaci pliku WARC do załadowania np na replayweb.page) - może kiedyś wystawię.

**Comment by M3n747** [comment]
Niezły pomysł. Ja chciałem zrzucić pełnego screena z całej strony rosteru, ale jak widać spóźniłem się.
