### ISSUE TITLE
Feedback: PTW Exits

### ISSUE THREAD

**Issue by M3n747** [k3rni/teczki-polskiego-wrestlingu#63]
**Which page:** `a/ptw-exits.md`
**Your feedback:** 
Zdecydowanie na tej liście brakuje Rafiego, jako pierwszego, który odszedł z PTW na rzecz PpW. Dokładnych dat nie podam, ale zapewne pokrywają się z jego ostatnią galą w Chorzowie i pierwszą w Warszawie.

**Comment by k3rni** [comment]
Added, sorted roughly chronologically in 1080fae
