### ISSUE TITLE
Feedback: PpW Ledwo Legalne IV

### ISSUE THREAD

**Issue by UltimoCombo** [k3rni/teczki-polskiego-wrestlingu#64]
**Which page:** `e/ppw/2024-06-08-ppw-ledwo-legalne-4.md`
**Your feedback:** 
<type your feedback here>
ok, i  forgot i cant speak english

**Comment by k3rni** [comment]
Publikować będziemy po angielsku, natomiast feedback akceptujemy również po polsku! Np zobacz tu https://github.com/k3rni/teczki-polskiego-wrestlingu/issues/62.

A ja poprawie instrukcje do zgłaszania żeby było to oczywiste, i nie odstraszało od współpracy.

**Comment by k3rni** [comment]
Added in f40b14b
