### ISSUE TITLE
Feedback: PpW Supershow

### ISSUE THREAD

**Issue by M3n747** [k3rni/teczki-polskiego-wrestlingu#65]
**Which page:** `e/ppw/2021-07-30-ppw-poznan-supershow.md`
**Your feedback:** 

Pełna karta:

Dzień 1:
Superior vs Cade Bruce
Direk vs Tony Sk1n
Hirinus vs 2 Chamy (Handicap Match)
Isnorr vs Adam Wong
Esteban Lucha vs Czacha
Esteban Lucha vs Adam Wong
Isnorr vs Hades
Royal Rumble match (Rob Scaffold vs Tony Sk1n vs Adam Wong vs Cade Bruce vs Isnorr vs Czacha vs Steven Kimono vs Direk vs Hades)

Dzień 2:
Isnorr vs Esteban Lucha
Rob Scaffold vs Aron Wake
Hades vs Tony Sk1n
Cade Bruce vs Madman Charlie
Johnny Blade vs Adam Wong
Isnorr vs Bonus CBD

Źródło:
https://web.archive.org/web/20230821192015/https://ppwofficial.fandom.com/pl/wiki/Pozna%C5%84_SuperShow_2021
https://ppw-fandom.tpwres.pl/poznan-supershow-2021

Niestety, nie ma tam podanych wyników, a raport wideo nie uwzględnia wszystkich walk.

**Comment by M3n747** [comment]
Aha, no i w sumie gala nazywała się "Poznań SuperShow 2021".

**Comment by k3rni** [comment]
4c66ea0
