### ISSUE TITLE
Feedback: Prime Time Wrestling

### ISSUE THREAD

**Issue by SewiTheRef** [k3rni/teczki-polskiego-wrestlingu#67]
**Which page:** `o/ptw.md`
**Your feedback:** 
<More high-profile exits:
"the greens" (AKA Zieloni / ZLN GNG) nie jest terminem określającym WSZYSTKICH ex-MZW zawodników, choć nazwa może sugerować inaczej. W praktyce jest to pokolenie zawodników, którzy dołączyli do MZW w latach 2017/2018 i utworzyli silnie związaną grupę towarzyską opartą na wrestlingu. Członkami Zielonych są: Axel Fox, Boro, Sewi The Ref, Olgierd, Gabriel Queen, Vic Golden, Madman Charlie, Isnorr, Aron Wake, Jacob Crane, Rafael Kid oraz part-time Asmund i Justin Joy. Stąd do "zielonych" nie zalicza się np. Rafi Rarytas, Sambor, Shadow, czy inni MZW/ex-MZW wrestlerzy. 

Zieloni prócz bycia grupą towarzyską opartą na wrestlingu była jednym ze "stronnictw" w Prime Time Wrestling (zaraz obok tzw "orginalsów"(ludzie wywodzący się wyłącznie z PTW) oraz "niebieskich" (ex-KPW), co powodowało wewnętrzne tarcia między poszczególnymi grupami, a zarządem. Tarcia opierały się głównie na różnicach w podejściu do jakości i filozofii wrestlingu (przykładowo: zbyt surowe wymagania Justina Joya gdy był jeszcze trenerem)
Podsumowując: jeżeli chodzi o status zielonych w kontekście polskiej sceny to najbliższym znanym w pro wrestlingu określeniem byłoby przyrównanie Zielonych do The Kliq z WWE. Po prostu jedna z grup wpływu aktywna najbardziej w PTW, lecz ostatnimi czasy również w ppw ewenement. 
Choć informacje mogą nie być przydatne teraz, to jednak zmotywowały mnie do zaraportowania tego, by być może w przyszłości stworzyć osobny artykuł o wewnętrznych konfliktach w PTW, lub po prostu o grupach aktywnych na polskiej scenie.

Source: obserwacja własna.>

**Comment by k3rni** [comment]
Added a standalone article in 0aabed0, linked from two places: Boro's group photo description, and Fox's article.
