### ISSUE TITLE
Feedback: PTW Exits

### ISSUE THREAD

**Issue by SewiTheRef** [k3rni/teczki-polskiego-wrestlingu#68]
**Which page:** `a/ptw-exits.md`
**Your feedback:** 
<Wrestlers & Personnel:
- Vic Golden: joined 2022
- Gabriel Queen: joined 2021
- Olgierd: joined 2021-11
- Rafi Rarytas: joined 2022 (MZW), exit date 2023-10-03 via instagram
-  Justin Joy joined 2021-10, exit date 2023-04

Staff:
- Arek Paterek: Joined 2021, last apperance 2024-05-11
- Łukasz "Balik: Baliński: Last: 2024-05-11
- Referee Seweryn: Joined 2021-11, first apperance 2022-01-23, last app 2024-05-11

source: insider info>

![RafiExit1](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/173069994/d4afc25a-cb0d-4d78-bd6e-e3ea18513674)

**Comment by k3rni** [comment]
Updated in 0395601, also added the above screenshot and some others copied from PTW's page.
