### ISSUE TITLE
Feedback: PPW Kiedyś Będzie Lepiej

### ISSUE THREAD

**Issue by M3n747** [k3rni/teczki-polskiego-wrestlingu#72]
**Which page:** `e/ppw/2019-07-19-ppw-kiedys-bedzie-lepiej.md`
**Your feedback:** 
Jeff to był Michael HT:
https://www.youtube.com/live/VlBjnWJRarE?si=LBRL38AjOmYrxW80&t=188

**Comment by k3rni** [comment]
Linked in 05cc70a
