### ISSUE TITLE
Create page: PPW: Ale grzeje

### ISSUE THREAD

**Issue by iwulOG** [k3rni/teczki-polskiego-wrestlingu#77]
2024-07-13, Teatr Komuna.

PpW announced its next show, which is the second set in Teatr Komuna, after Miasto Bezprawia.
Announcement post featured an official poster, focusing on the term "Zmowa" (roughly translated as "conspiracy", maybe a better term is there?), promising the hottest (figuratively and literally) show of the summer. The hype text suggested a "conspiracy against conspiracy" - Biesiad's idea to get his revenge and thwart Mister Zet's and Gryffin's new alliance that screwed Biesiad of his newly won PpW Championship (Ledwo Legalne 4)

Prior to the show, PpW is going to hold a 5-day open seminar ("summer course") with Jacob Crane
References:
https://www.facebook.com/photo/?fbid=976634991133560&set=a.499910772139320
![image](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/8ee4f19c-0122-4ac7-ae60-20a3fd44e2b0)
Summer course
https://www.facebook.com/events/1409438239775557/?acontext=%7B%22event_action_history%22%3A[]%7D

**Comment by M3n747** [comment]
"Collusion"? Nie brzmi równie dobrze, co "conspiracy", ale chyba lepiej oddaje znaczenie "zmowy".
https://dictionary.cambridge.org/dictionary/english/collusion

**Comment by k3rni** [comment]
Collusion lepsze, użyję

**Comment by k3rni** [comment]
Added in ee1b8ae
