### ISSUE TITLE
Feedback on page: Do Or Die Wrestling

### ISSUE THREAD

**Issue by iwulOG** [k3rni/teczki-polskiego-wrestlingu#8]
**Which page ?** `o/ddw.md`
**Your feedback:**
<Add references:
Historia Polskiego Wrestlingu #2 – Próby ponownego wprowadzenia wrestlingu do Polski, Początki DDW, Wielka gala w Stodole https://mywrestling.com.pl/historia-polskiego-wrestlingu-2-proby-ponownego-wprowadzenia-wrestlingu-do-polski-poczatki-ddw-wielka-gala-w-stodole/
>

**Comment by k3rni** [comment]
Already there (as "article on Mywrestling"), but changed the link text in 61e3858.
