### ISSUE TITLE
Feedback: Mutant

### ISSUE THREAD

**Issue by iwulOG** [k3rni/teczki-polskiego-wrestlingu#83]
![Screenshot_20240622-143521_Instagram](https://github.com/k3rni/teczki-polskiego-wrestlingu/assets/155029200/3d681a32-9f22-40e8-93db-3d1c041d19b8)
We've got some more Mutant's matches as per his own declaration. With secondary sources we might be able to create a full page for him. Declared matches seem to be from Daniel Boza, merging the records make him meet the criteria for own talent page
Example reference
https://kpwrestling.pl/events/kpw-arena-16/

**Comment by k3rni** [comment]
Basic page added in 8a08c7f
